-- MySQL Script generated by MySQL Workbench
-- 05/03/17 05:20:28
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema matcha
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `matcha` ;

-- -----------------------------------------------------
-- Schema matcha
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `matcha` DEFAULT CHARACTER SET utf8 ;
USE `matcha` ;

-- -----------------------------------------------------
-- Table `matcha`.`t_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `matcha`.`t_user` ;

CREATE TABLE IF NOT EXISTS `matcha`.`t_user` (
  `usr_id` INT NOT NULL AUTO_INCREMENT,
  `usr_email` VARCHAR(255) NULL,
  `usr_password` VARCHAR(255) NULL,
  `usr_token` VARCHAR(255) NULL,
  PRIMARY KEY (`usr_id`),
  UNIQUE INDEX `usr_token_UNIQUE` (`usr_token` ASC),
  UNIQUE INDEX `usr_email_UNIQUE` (`usr_email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `matcha`.`t_tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `matcha`.`t_tag` ;

CREATE TABLE IF NOT EXISTS `matcha`.`t_tag` (
  `tag_id` INT NOT NULL AUTO_INCREMENT,
  `tag_content` VARCHAR(45) NULL,
  PRIMARY KEY (`tag_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `matcha`.`t_user_has_t_tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `matcha`.`t_user_has_t_tag` ;

CREATE TABLE IF NOT EXISTS `matcha`.`t_user_has_t_tag` (
  `usr_id` INT NOT NULL,
  `tag_id` INT NOT NULL,
  PRIMARY KEY (`usr_id`, `tag_id`),
  INDEX `fk_t_user_has_t_tag_t_tag1_idx` (`tag_id` ASC),
  INDEX `fk_t_user_has_t_tag_t_user_idx` (`usr_id` ASC),
  CONSTRAINT `fk_t_user_has_t_tag_t_user`
    FOREIGN KEY (`usr_id`)
    REFERENCES `matcha`.`t_user` (`usr_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_user_has_t_tag_t_tag1`
    FOREIGN KEY (`tag_id`)
    REFERENCES `matcha`.`t_tag` (`tag_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `matcha`.`t_user_meta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `matcha`.`t_user_meta` ;

CREATE TABLE IF NOT EXISTS `matcha`.`t_user_meta` (
  `meta_name` VARCHAR(45) NOT NULL,
  `meta_value` TEXT NULL,
  `usr_id` INT NOT NULL,
  PRIMARY KEY (`meta_name`, `usr_id`),
  INDEX `fk_t_user_meta_t_user1_idx` (`usr_id` ASC),
  UNIQUE INDEX `usr_id_UNIQUE` (`usr_id` ASC, `meta_name` ASC),
  UNIQUE INDEX `meta_name_UNIQUE` (`meta_name` ASC, `usr_id` ASC),
  CONSTRAINT `fk_t_user_meta_t_user1`
    FOREIGN KEY (`usr_id`)
    REFERENCES `matcha`.`t_user` (`usr_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
